export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  USER: '/user',
  USER_MANAGEMENT: '/user/user_management',
  CREATE_NEW_USER: '/user/create_user',
  NOTIFICATION: '/notification',
  NOTIFICATION_MANAGEMENT: '/notification/notification_management',
  CREATE_NEW_NOTIFICATION: '/notification/create_notification',
  CREATE_NEW_SEGMENT: '/notification/create_new_segment',
  EDIT_SEGMENT: '/notification/edit_segment',
  SEGMENT_MANAGEMENT: '/notification/segment_management',
  SUBSCRIBERS: '/notification/subscribers',
  LOGIN: '/login',
  ARTICLE: '/article',
  CREATE_NEW_ARTICLES: '/article/create_article',
  ARTICLES_MANAGEMENT: '/article/articles_management',
  REPORT: '/report',
};
